language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

    # Additional components
    #- extra-google-google_play_services
    #- addon-google_apis-google-19

script:
  - ./gradlew assembleRelease

licenses:
    - '.+'